spring:
  application:
    name: market

  # 1. 데이터베이스 접속 설정 (MySQL)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      # update: 엔티티 수정 시 테이블 구조를 자동으로 반영
      # create: 서버 켤 때마다 테이블을 다 밀고 새로 생성
      # validate: 엔티티와 테이블의 매핑을 확인(실제 운영할 때 사용)
      ddl-auto: update
    show-sql: true           # 콘솔에 실행 SQL 출력
    properties:
      hibernate:
        format_sql: true     # SQL을 가독성 좋게 정렬
        dialect: org.hibernate.dialect.MySQLDialect		#방언 설정
  config:
    import: application-oauth2.yaml

  cloud:
    aws:
      credentials:
        access-key: ${S3_ACCESS_KEY}
        secret-key: ${S3_SECRET_KEY}
      s3:
        bucket: ${S3_BUCKET_NAME}
      region:
        static: ap-northeast-2

logging:
  level:
    org.hibernate.SQL: debug              # 실행 SQL 로그 레벨
    org.hibernate.orm.jdbc.bind: trace    # SQL에 담긴 실제 파라미터(값) 확인

server:
  port: 8080
  address: 0.0.0.0

file:
  upload:
    itemImgLocation: s3